<?php
//TODO DO ALL TODO VALIDATION OF THE ALL ENTITIES IN THE SYSTEM

//TODO MAKE THE FUNCTION OF THE SOFT DELETE TESTING

//TODO CREATE ORDER SYSTEM

//TODO IMPLEMENT THE PERMISSIONS SYSTEM IN THE METHODS AND THE ROUTES

//TODO DO FORCE DELETE AND RESTORE FOR ALL ENTITIES AND AND SET MULTIPLE DELETE FOR THEM IN FORCE DELETE AND NORMAL DELETE AND MULTIPLE RESTORE AND SINGLE RESTORE FOR ALL ENTITIES

//TODO CREATE BASKET SERVICE

//TODO CREATE VIP SYSTEM IN THE PROJECT

//TODO CREATE USE PANEL

//TODO CREATE ALL API DOCUMENTS

//TODO CREATE DISCOUNT SYSTEM


